# Generated by Django 3.1.7 on 2021-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication_text', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
    ]
